- name: "[Ubuntu] Install packages"
  include_tasks: install_ubuntu_packages.yml
  when:
  - input_role_os_distribution == "Ubuntu"

- name: "[CentOS] Install packages"
  include_tasks: install_centos_packages.yml
  when:
  - input_role_os_distribution == "CentOS"

- name: "[CentOS] Install packages"
  include_tasks: install_redhat_packages.yml
  when:
  - input_role_os_distribution == "RedHat"